{
 "title": "Link Simulator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "session_id",
    "query": "SELECT last(\"session\") FROM link_config"
   },
   {
    "name": "current_links",
    "query": "SHOW TAG VALUES FROM link_config WITH KEY  = \"name\" WHERE \"session_tag\" =~ /^$session_id/"
   }
  ]
 },
 "panels": [
  { "title": "$current_links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "current_links" },
  {
   "title": "Link Information",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"name\") FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"recv_b\" FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Forwarded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"forw_b\" FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Dropped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"drop_b\" FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"inbound\") FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"outbound\") FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delay",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"delay\") FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bit Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ber\") FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "query": "SELECT last(\"bandwidth\")/1000 FROM \"link_config\" WHERE \"session_tag\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "link_stat0",
     "query": "SELECT \"rate\" FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Packet Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"recv_p\") FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dropped Packet Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"drop_p\") FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forwarded Packet Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"forw_p\") FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bit Flips",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"flips\") FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Internal Buffer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"buffer\") *100 FROM \"link_stat\" WHERE \"session\" =~ /^$session_id/ AND \"name\" =~/^$current_links/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}